import {authConfig} from './auth-config.js?v=20260926-1';
const $=id=>document.getElementById(id);let client,user,profiles=[];
const el=(t,x,c)=>{const n=document.createElement(t);if(x!==undefined)n.textContent=x;if(c)n.className=c;return n};
const fmt=d=>d?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(d)):'—';
async function setReport(id,status){const {error}=await client.from('user_reports').update({status}).eq('id',id);$('status').textContent=error?error.message:'Report updated.';if(!error)await load()}
async function setListing(userId,status){const note=status==='suspended'?(prompt('Moderation note (optional)')||''):null;const {error}=await client.from('companion_listings').update({moderation_status:status,moderation_note:note}).eq('user_id',userId);$('status').textContent=error?error.message:'Listing updated.';if(!error)await load()}
function reportCard(r){const n=el('article',undefined,'booking-card');n.append(el('h3',r.reason),el('p',r.details||'No extra details.','booking-note'),el('span',r.status,'status-pill'));const a=el('div',undefined,'admin-actions');for(const s of ['reviewed','actioned','dismissed']){const b=el('button',s,'button button-outline');b.onclick=()=>void setReport(r.id,s);a.append(b)}n.append(a);return n}
function listingCard(r){const n=el('article',undefined,'booking-card');n.append(el('h3',r.display_name),el('p',r.bio,'booking-note'),el('span',r.moderation_status,'status-pill'));const a=el('div',undefined,'admin-actions'),s=el('button',r.moderation_status==='active'?'Suspend':'Restore','button button-outline');s.onclick=()=>void setListing(r.user_id,r.moderation_status==='active'?'suspended':'active');a.append(s);n.append(a);return n}
function userCard(p){const n=el('article',undefined,'booking-card admin-user-card');const top=el('div',undefined,'booking-top');top.append(el('h3',p.display_name||'Unnamed member'),el('code',p.safety_id||'No Safety ID','safety-code'));n.append(top,el('p','Internal ID: '+p.user_id,'booking-note'));const meta=el('div',undefined,'booking-meta');meta.append(el('span',p.profile_kind||'member'),el('span',p.email_verified_at?'Email verified':'Email not verified'),el('span','Joined '+fmt(p.joined_at)));n.append(meta);return n}
function renderUsers(){const q=$('user-search').value.trim().toLowerCase();const rows=!q?profiles:profiles.filter(p=>[p.display_name,p.safety_id,p.user_id].some(v=>String(v||'').toLowerCase().includes(q)));$('users').replaceChildren(...rows.map(userCard));$('user-count').textContent=rows.length+' user'+(rows.length===1?'':'s')+' shown.'}
async function load(){
 const [rr,ll,pp]=await Promise.all([
  client.from('user_reports').select('*').order('created_at',{ascending:false}),
  client.from('companion_listings').select('user_id,display_name,bio,published,moderation_status,moderation_note').order('display_name'),
  client.from('member_profiles').select('user_id,display_name,profile_kind,safety_id,joined_at,email_verified_at').order('display_name')
 ]);
 if(rr.error||ll.error||pp.error)throw rr.error||ll.error||pp.error;
 profiles=pp.data||[];$('reports').replaceChildren(...(rr.data||[]).map(reportCard));$('listings').replaceChildren(...(ll.data||[]).map(listingCard));renderUsers();$('admin-content').hidden=false;$('status').textContent='';
}
async function init(){try{if(!globalThis.supabase)throw Error('Services unavailable');client=globalThis.supabase.createClient(authConfig.supabaseUrl,authConfig.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:'sathivo.auth.v1'}});const u=await client.auth.getUser();user=u.data.user;if(!user){location.replace('account.html#login');return}const a=await client.from('platform_admins').select('role').eq('user_id',user.id).maybeSingle();if(a.error||!a.data)throw Error('This account is not authorized for Sathivo admin.');$('user-search').addEventListener('input',renderUsers);await load()}catch(e){$('status').textContent=e.message||'Could not load admin.'}}
void init();