-- Expand Sathivo location coverage to every state/UT district while keeping the current
-- lightweight client-side dropdown architecture. Source snapshot: official-government-derived
-- India states/districts dataset (36 states/UTs, 784 districts), fetched 2026-10-06.
-- "District-wide" is a deliberate fallback for users whose exact city/town is not yet in
-- profile_locations; existing highlighted cities/towns remain unchanged.

create sequence if not exists public.profile_locations_id_seq;
alter sequence public.profile_locations_id_seq owned by public.profile_locations.id;

select setval(
  'public.profile_locations_id_seq',
  greatest(coalesce((select max(id) from public.profile_locations),0)+1,1),
  false
);

alter table public.profile_locations
  alter column id set default nextval('public.profile_locations_id_seq');

insert into public.profile_locations(state,district,city)
values
('Andaman and Nicobar Islands','Nicobars','District-wide'),
('Andaman and Nicobar Islands','North And Middle Andaman','District-wide'),
('Andaman and Nicobar Islands','South Andamans','District-wide'),
('Andhra Pradesh','Alluri Sitharama Raju','District-wide'),
('Andhra Pradesh','Anakapalli','District-wide'),
('Andhra Pradesh','Ananthapuramu','District-wide'),
('Andhra Pradesh','Annamayya','District-wide'),
('Andhra Pradesh','Bapatla','District-wide'),
('Andhra Pradesh','Chittoor','District-wide'),
('Andhra Pradesh','Dr. B.R. Ambedkar Konaseema','District-wide'),
('Andhra Pradesh','East Godavari','District-wide'),
('Andhra Pradesh','Eluru','District-wide'),
('Andhra Pradesh','Guntur','District-wide'),
('Andhra Pradesh','Kakinada','District-wide'),
('Andhra Pradesh','Krishna','District-wide'),
('Andhra Pradesh','Kurnool','District-wide'),
('Andhra Pradesh','Markapuram','District-wide'),
('Andhra Pradesh','Nandyal','District-wide'),
('Andhra Pradesh','Ntr','District-wide'),
('Andhra Pradesh','Palnadu','District-wide'),
('Andhra Pradesh','Parvathipuram Manyam','District-wide'),
('Andhra Pradesh','Polavaram','District-wide'),
('Andhra Pradesh','Prakasam','District-wide'),
('Andhra Pradesh','Sri Potti Sriramulu Nellore','District-wide'),
('Andhra Pradesh','Sri Sathya Sai','District-wide'),
('Andhra Pradesh','Srikakulam','District-wide'),
('Andhra Pradesh','Tirupati','District-wide'),
('Andhra Pradesh','Visakhapatnam','District-wide'),
('Andhra Pradesh','Vizianagaram','District-wide'),
('Andhra Pradesh','West Godavari','District-wide'),
('Andhra Pradesh','Y.S.R. Kadapa','District-wide'),
('Arunachal Pradesh','Anjaw','District-wide'),
('Arunachal Pradesh','Bichom','District-wide'),
('Arunachal Pradesh','Changlang','District-wide'),
('Arunachal Pradesh','Dibang Valley','District-wide'),
('Arunachal Pradesh','East Kameng','District-wide'),
('Arunachal Pradesh','East Siang','District-wide'),
('Arunachal Pradesh','Kamle','District-wide'),
('Arunachal Pradesh','Keyi Panyor','District-wide'),
('Arunachal Pradesh','Kra Daadi','District-wide'),
('Arunachal Pradesh','Kurung Kumey','District-wide'),
('Arunachal Pradesh','Leparada','District-wide'),
('Arunachal Pradesh','Lohit','District-wide'),
('Arunachal Pradesh','Longding','District-wide'),
('Arunachal Pradesh','Lower Dibang Valley','District-wide'),
('Arunachal Pradesh','Lower Siang','District-wide'),
('Arunachal Pradesh','Lower Subansiri','District-wide'),
('Arunachal Pradesh','Namsai','District-wide'),
('Arunachal Pradesh','Pakke Kessang','District-wide'),
('Arunachal Pradesh','Papum Pare','District-wide'),
('Arunachal Pradesh','Shi Yomi','District-wide'),
('Arunachal Pradesh','Siang','District-wide'),
('Arunachal Pradesh','Tawang','District-wide'),
('Arunachal Pradesh','Tirap','District-wide'),
('Arunachal Pradesh','Upper Siang','District-wide'),
('Arunachal Pradesh','Upper Subansiri','District-wide'),
('Arunachal Pradesh','West Kameng','District-wide'),
('Arunachal Pradesh','West Siang','District-wide'),
('Assam','Bajali','District-wide'),
('Assam','Baksa','District-wide'),
('Assam','Barpeta','District-wide'),
('Assam','Biswanath','District-wide'),
('Assam','Bongaigaon','District-wide'),
('Assam','Cachar','District-wide'),
('Assam','Charaideo','District-wide'),
('Assam','Chirang','District-wide'),
('Assam','Darrang','District-wide'),
('Assam','Dhemaji','District-wide'),
('Assam','Dhubri','District-wide'),
('Assam','Dibrugarh','District-wide'),
('Assam','Dima Hasao','District-wide'),
('Assam','Goalpara','District-wide'),
('Assam','Golaghat','District-wide'),
('Assam','Hailakandi','District-wide'),
('Assam','Hojai','District-wide'),
('Assam','Jorhat','District-wide'),
('Assam','Kamrup','District-wide'),
('Assam','Kamrup Metro','District-wide'),
('Assam','Karbi Anglong','District-wide'),
('Assam','Kokrajhar','District-wide'),
('Assam','Lakhimpur','District-wide'),
('Assam','Majuli','District-wide'),
('Assam','Marigaon','District-wide'),
('Assam','Nagaon','District-wide'),
('Assam','Nalbari','District-wide'),
('Assam','Sivasagar','District-wide'),
('Assam','Sonitpur','District-wide'),
('Assam','South Salmara Mancachar','District-wide'),
('Assam','Sribhumi','District-wide'),
('Assam','Tamulpur','District-wide'),
('Assam','Tinsukia','District-wide'),
('Assam','Udalguri','District-wide'),
('Assam','West Karbi Anglong','District-wide'),
('Chandigarh','Chandigarh','District-wide'),
('Dadra and Nagar Haveli and Daman and Diu','Dadra And Nagar Haveli','District-wide'),
('Dadra and Nagar Haveli and Daman and Diu','Daman','District-wide'),
('Dadra and Nagar Haveli and Daman and Diu','Diu','District-wide'),
('Delhi','Central','District-wide'),
('Delhi','Central North','District-wide'),
('Delhi','East','District-wide'),
('Delhi','New Delhi','District-wide'),
('Delhi','North','District-wide'),
('Delhi','North East','District-wide'),
('Delhi','North West','District-wide'),
('Delhi','Old Delhi','District-wide'),
('Delhi','Outer North','District-wide'),
('Delhi','South','District-wide'),
('Delhi','South East','District-wide'),
('Delhi','South West','District-wide'),
('Delhi','West','District-wide'),
('Goa','Kushavati','District-wide'),
('Goa','North Goa','District-wide'),
('Goa','South Goa','District-wide'),
('Bihar','Araria','District-wide'),
('Bihar','Arwal','District-wide'),
('Bihar','Aurangabad','District-wide'),
('Bihar','Banka','District-wide'),
('Bihar','Begusarai','District-wide'),
('Bihar','Bhagalpur','District-wide'),
('Bihar','Bhojpur','District-wide'),
('Bihar','Buxar','District-wide'),
('Bihar','Darbhanga','District-wide'),
('Bihar','Gaya','District-wide'),
('Bihar','Gopalganj','District-wide'),
('Bihar','Jamui','District-wide'),
('Bihar','Jehanabad','District-wide'),
('Bihar','Kaimur (Bhabua)','District-wide'),
('Bihar','Katihar','District-wide'),
('Bihar','Khagaria','District-wide'),
('Bihar','Kishanganj','District-wide'),
('Bihar','Lakhisarai','District-wide'),
('Bihar','Madhepura','District-wide'),
('Bihar','Madhubani','District-wide'),
('Bihar','Munger','District-wide'),
('Bihar','Muzaffarpur','District-wide'),
('Bihar','Nalanda','District-wide'),
('Bihar','Nawada','District-wide'),
('Bihar','Pashchim Champaran','District-wide'),
('Bihar','Patna','District-wide'),
('Bihar','Purbi Champaran','District-wide'),
('Bihar','Purnia','District-wide'),
('Bihar','Rohtas','District-wide'),
('Bihar','Saharsa','District-wide'),
('Bihar','Samastipur','District-wide'),
('Bihar','Saran','District-wide'),
('Bihar','Sheikhpura','District-wide'),
('Bihar','Sheohar','District-wide'),
('Bihar','Sitamarhi','District-wide'),
('Bihar','Siwan','District-wide'),
('Bihar','Supaul','District-wide'),
('Bihar','Vaishali','District-wide'),
('Chhattisgarh','Balod','District-wide'),
('Chhattisgarh','Balodabazar-Bhatapara','District-wide'),
('Chhattisgarh','Balrampur-Ramanujganj','District-wide'),
('Chhattisgarh','Bastar','District-wide'),
('Chhattisgarh','Bemetara','District-wide'),
('Chhattisgarh','Bijapur','District-wide'),
('Chhattisgarh','Bilaspur','District-wide'),
('Chhattisgarh','Dakshin Bastar Dantewada','District-wide'),
('Chhattisgarh','Dhamtari','District-wide'),
('Chhattisgarh','Durg','District-wide'),
('Chhattisgarh','Gariyaband','District-wide'),
('Chhattisgarh','Gaurela-Pendra-Marwahi','District-wide'),
('Chhattisgarh','Janjgir-Champa','District-wide'),
('Chhattisgarh','Jashpur','District-wide'),
('Chhattisgarh','Kabeerdham','District-wide'),
('Chhattisgarh','Khairagarh-Chhuikhadan-Gandai','District-wide'),
('Chhattisgarh','Kondagaon','District-wide'),
('Chhattisgarh','Korba','District-wide'),
('Chhattisgarh','Korea','District-wide'),
('Chhattisgarh','Mahasamund','District-wide'),
('Chhattisgarh','Manendragarh-Chirmiri-Bharatpur(M C B)','District-wide'),
('Chhattisgarh','Mohla-Manpur-Ambagarh Chouki','District-wide'),
('Chhattisgarh','Mungeli','District-wide'),
('Chhattisgarh','Narayanpur','District-wide'),
('Chhattisgarh','Raigarh','District-wide'),
('Chhattisgarh','Raipur','District-wide'),
('Chhattisgarh','Rajnandgaon','District-wide'),
('Chhattisgarh','Sakti','District-wide'),
('Chhattisgarh','Sarangarh-Bilaigarh','District-wide'),
('Chhattisgarh','Sukma','District-wide'),
('Chhattisgarh','Surajpur','District-wide'),
('Chhattisgarh','Surguja','District-wide'),
('Chhattisgarh','Uttar Bastar Kanker','District-wide'),
('Haryana','Ambala','District-wide'),
('Haryana','Bhiwani','District-wide'),
('Haryana','Charkhi Dadri','District-wide'),
('Haryana','Faridabad','District-wide'),
('Haryana','Fatehabad','District-wide'),
('Haryana','Gurugram','District-wide'),
('Haryana','Hansi','District-wide'),
('Haryana','Hisar','District-wide'),
('Haryana','Jhajjar','District-wide'),
('Haryana','Jind','District-wide'),
('Haryana','Kaithal','District-wide'),
('Haryana','Karnal','District-wide'),
('Haryana','Kurukshetra','District-wide'),
('Haryana','Mahendragarh','District-wide'),
('Haryana','Nuh','District-wide'),
('Haryana','Palwal','District-wide'),
('Haryana','Panchkula','District-wide'),
('Haryana','Panipat','District-wide'),
('Haryana','Rewari','District-wide'),
('Haryana','Rohtak','District-wide'),
('Haryana','Sirsa','District-wide'),
('Haryana','Sonipat','District-wide'),
('Haryana','Yamunanagar','District-wide'),
('Jammu and Kashmir','Anantnag','District-wide'),
('Jammu and Kashmir','Bandipora','District-wide'),
('Jammu and Kashmir','Baramulla','District-wide'),
('Jammu and Kashmir','Budgam','District-wide'),
('Jammu and Kashmir','Doda','District-wide'),
('Jammu and Kashmir','Ganderbal','District-wide'),
('Jammu and Kashmir','Jammu','District-wide'),
('Jammu and Kashmir','Kathua','District-wide'),
('Jammu and Kashmir','Kishtwar','District-wide'),
('Jammu and Kashmir','Kulgam','District-wide'),
('Jammu and Kashmir','Kupwara','District-wide'),
('Jammu and Kashmir','Poonch','District-wide'),
('Jammu and Kashmir','Pulwama','District-wide'),
('Jammu and Kashmir','Rajouri','District-wide'),
('Jammu and Kashmir','Ramban','District-wide'),
('Jammu and Kashmir','Reasi','District-wide'),
('Jammu and Kashmir','Samba','District-wide'),
('Jammu and Kashmir','Shopian','District-wide'),
('Jammu and Kashmir','Srinagar','District-wide'),
('Jammu and Kashmir','Udhampur','District-wide'),
('Gujarat','Ahmedabad','District-wide'),
('Gujarat','Amreli','District-wide'),
('Gujarat','Anand','District-wide'),
('Gujarat','Arvalli','District-wide'),
('Gujarat','Banas Kantha','District-wide'),
('Gujarat','Bharuch','District-wide'),
('Gujarat','Bhavnagar','District-wide'),
('Gujarat','Botad','District-wide'),
('Gujarat','Chhotaudepur','District-wide'),
('Gujarat','Dahod','District-wide'),
('Gujarat','Dangs','District-wide'),
('Gujarat','Devbhumi Dwarka','District-wide'),
('Gujarat','Gandhinagar','District-wide'),
('Gujarat','Gir Somnath','District-wide'),
('Gujarat','Jamnagar','District-wide'),
('Gujarat','Junagadh','District-wide'),
('Gujarat','Kachchh','District-wide'),
('Gujarat','Kheda','District-wide'),
('Gujarat','Mahesana','District-wide'),
('Gujarat','Mahisagar','District-wide'),
('Gujarat','Morbi','District-wide'),
('Gujarat','Narmada','District-wide'),
('Gujarat','Navsari','District-wide'),
('Gujarat','Panch Mahals','District-wide'),
('Gujarat','Patan','District-wide'),
('Gujarat','Porbandar','District-wide'),
('Gujarat','Rajkot','District-wide'),
('Gujarat','Sabar Kantha','District-wide'),
('Gujarat','Surat','District-wide'),
('Gujarat','Surendranagar','District-wide'),
('Gujarat','Tapi','District-wide'),
('Gujarat','Vadodara','District-wide'),
('Gujarat','Valsad','District-wide'),
('Gujarat','Vav-Tharad','District-wide'),
('Jharkhand','Bokaro','District-wide'),
('Jharkhand','Chatra','District-wide'),
('Jharkhand','Deoghar','District-wide'),
('Jharkhand','Dhanbad','District-wide'),
('Jharkhand','Dumka','District-wide'),
('Jharkhand','East Singhbum','District-wide'),
('Jharkhand','Garhwa','District-wide'),
('Jharkhand','Giridih','District-wide'),
('Jharkhand','Godda','District-wide'),
('Jharkhand','Gumla','District-wide'),
('Jharkhand','Hazaribagh','District-wide'),
('Jharkhand','Jamtara','District-wide'),
('Jharkhand','Khunti','District-wide'),
('Jharkhand','Koderma','District-wide'),
('Jharkhand','Latehar','District-wide'),
('Jharkhand','Lohardaga','District-wide'),
('Jharkhand','Pakur','District-wide'),
('Jharkhand','Palamu','District-wide'),
('Jharkhand','Ramgarh','District-wide'),
('Jharkhand','Ranchi','District-wide'),
('Jharkhand','Sahebganj','District-wide'),
('Jharkhand','Saraikela Kharsawan','District-wide'),
('Jharkhand','Simdega','District-wide'),
('Jharkhand','West Singhbhum','District-wide'),
('Kerala','Alappuzha','District-wide'),
('Kerala','Ernakulam','District-wide'),
('Kerala','Idukki','District-wide'),
('Kerala','Kannur','District-wide'),
('Kerala','Kasaragod','District-wide'),
('Kerala','Kollam','District-wide'),
('Kerala','Kottayam','District-wide'),
('Kerala','Kozhikode','District-wide'),
('Kerala','Malappuram','District-wide'),
('Kerala','Palakkad','District-wide'),
('Kerala','Pathanamthitta','District-wide'),
('Kerala','Thiruvananthapuram','District-wide'),
('Kerala','Thrissur','District-wide'),
('Kerala','Wayanad','District-wide'),
('Ladakh','Kargil','District-wide'),
('Ladakh','Leh Ladakh','District-wide'),
('Lakshadweep','Lakshadweep District','District-wide'),
('Karnataka','Bagalkote','District-wide'),
('Karnataka','Ballari','District-wide'),
('Karnataka','Belagavi','District-wide'),
('Karnataka','Bengaluru Rural','District-wide'),
('Karnataka','Bengaluru South','District-wide'),
('Karnataka','Bengaluru Urban','District-wide'),
('Karnataka','Bidar','District-wide'),
('Karnataka','Chamarajanagar','District-wide'),
('Karnataka','Chikkaballapura','District-wide'),
('Karnataka','Chikkamagaluru','District-wide'),
('Karnataka','Chitradurga','District-wide'),
('Karnataka','Dakshina Kannada','District-wide'),
('Karnataka','Davanagere','District-wide'),
('Karnataka','Dharwad','District-wide'),
('Karnataka','Gadag','District-wide'),
('Karnataka','Hassan','District-wide'),
('Karnataka','Haveri','District-wide'),
('Karnataka','Kalaburagi','District-wide'),
('Karnataka','Kodagu','District-wide'),
('Karnataka','Kolar','District-wide'),
('Karnataka','Koppal','District-wide'),
('Karnataka','Mandya','District-wide'),
('Karnataka','Mysuru','District-wide'),
('Karnataka','Raichur','District-wide'),
('Karnataka','Shivamogga','District-wide'),
('Karnataka','Tumakuru','District-wide'),
('Karnataka','Udupi','District-wide'),
('Karnataka','Uttara Kannada','District-wide'),
('Karnataka','Vijayanagara','District-wide'),
('Karnataka','Vijayapura','District-wide'),
('Karnataka','Yadgir','District-wide'),
('Himachal Pradesh','Bilaspur','District-wide'),
('Himachal Pradesh','Chamba','District-wide'),
('Himachal Pradesh','Hamirpur','District-wide'),
('Himachal Pradesh','Kangra','District-wide'),
('Himachal Pradesh','Kinnaur','District-wide'),
('Himachal Pradesh','Kullu','District-wide'),
('Himachal Pradesh','Lahaul And Spiti','District-wide'),
('Himachal Pradesh','Mandi','District-wide'),
('Himachal Pradesh','Shimla','District-wide'),
('Himachal Pradesh','Sirmaur','District-wide'),
('Himachal Pradesh','Solan','District-wide'),
('Himachal Pradesh','Una','District-wide'),
('Manipur','Bishnupur','District-wide'),
('Manipur','Chandel','District-wide'),
('Manipur','Churachandpur','District-wide'),
('Manipur','Imphal East','District-wide'),
('Manipur','Imphal West','District-wide'),
('Manipur','Jiribam','District-wide'),
('Manipur','Kakching','District-wide'),
('Manipur','Kamjong','District-wide'),
('Manipur','Kangpokpi','District-wide'),
('Manipur','Noney','District-wide'),
('Manipur','Pherzawl','District-wide'),
('Manipur','Senapati','District-wide'),
('Manipur','Tamenglong','District-wide'),
('Manipur','Tengnoupal','District-wide'),
('Manipur','Thoubal','District-wide'),
('Manipur','Ukhrul','District-wide'),
('Meghalaya','East Garo Hills','District-wide'),
('Meghalaya','East Jaintia Hills','District-wide'),
('Meghalaya','East Khasi Hills','District-wide'),
('Meghalaya','Eastern West Khasi Hills','District-wide'),
('Meghalaya','North Garo Hills','District-wide'),
('Meghalaya','Ri Bhoi','District-wide'),
('Meghalaya','South Garo Hills','District-wide'),
('Meghalaya','South West Garo Hills','District-wide'),
('Meghalaya','South West Khasi Hills','District-wide'),
('Meghalaya','West Garo Hills','District-wide'),
('Meghalaya','West Jaintia Hills','District-wide'),
('Meghalaya','West Khasi Hills','District-wide'),
('Mizoram','Aizawl','District-wide'),
('Mizoram','Champhai','District-wide'),
('Mizoram','Hnahthial','District-wide'),
('Mizoram','Khawzawl','District-wide'),
('Mizoram','Kolasib','District-wide'),
('Mizoram','Lawngtlai','District-wide'),
('Mizoram','Lunglei','District-wide'),
('Mizoram','Mamit','District-wide'),
('Mizoram','Saitual','District-wide'),
('Mizoram','Serchhip','District-wide'),
('Mizoram','Siaha','District-wide'),
('Maharashtra','Ahilyanagar','District-wide'),
('Maharashtra','Akola','District-wide'),
('Maharashtra','Amravati','District-wide'),
('Maharashtra','Beed','District-wide'),
('Maharashtra','Bhandara','District-wide'),
('Maharashtra','Buldhana','District-wide'),
('Maharashtra','Chandrapur','District-wide'),
('Maharashtra','Chhatrapati Sambhajinagar','District-wide'),
('Maharashtra','Dharashiv','District-wide'),
('Maharashtra','Dhule','District-wide'),
('Maharashtra','Gadchiroli','District-wide'),
('Maharashtra','Gondia','District-wide'),
('Maharashtra','Hingoli','District-wide'),
('Maharashtra','Jalgaon','District-wide'),
('Maharashtra','Jalna','District-wide'),
('Maharashtra','Kolhapur','District-wide'),
('Maharashtra','Latur','District-wide'),
('Maharashtra','Mumbai','District-wide'),
('Maharashtra','Mumbai Suburban','District-wide'),
('Maharashtra','Nagpur','District-wide'),
('Maharashtra','Nanded','District-wide'),
('Maharashtra','Nandurbar','District-wide'),
('Maharashtra','Nashik','District-wide'),
('Maharashtra','Palghar','District-wide'),
('Maharashtra','Parbhani','District-wide'),
('Maharashtra','Pune','District-wide'),
('Maharashtra','Raigad','District-wide'),
('Maharashtra','Ratnagiri','District-wide'),
('Maharashtra','Sangli','District-wide'),
('Maharashtra','Satara','District-wide'),
('Maharashtra','Sindhudurg','District-wide'),
('Maharashtra','Solapur','District-wide'),
('Maharashtra','Thane','District-wide'),
('Maharashtra','Wardha','District-wide'),
('Maharashtra','Washim','District-wide'),
('Maharashtra','Yavatmal','District-wide'),
('Nagaland','Chumoukedima','District-wide'),
('Nagaland','Dimapur','District-wide'),
('Nagaland','Kiphire','District-wide'),
('Nagaland','Kohima','District-wide'),
('Nagaland','Longleng','District-wide'),
('Nagaland','Meluri','District-wide'),
('Nagaland','Mokokchung','District-wide'),
('Nagaland','Mon','District-wide'),
('Nagaland','Niuland','District-wide'),
('Nagaland','Noklak','District-wide'),
('Nagaland','Peren','District-wide'),
('Nagaland','Phek','District-wide'),
('Nagaland','Shamator','District-wide'),
('Nagaland','Tseminyu','District-wide'),
('Nagaland','Tuensang','District-wide'),
('Nagaland','Wokha','District-wide'),
('Nagaland','Zunheboto','District-wide'),
('Puducherry','Karaikal','District-wide'),
('Puducherry','Puducherry','District-wide'),
('Punjab','Amritsar','District-wide'),
('Punjab','Barnala','District-wide'),
('Punjab','Bathinda','District-wide'),
('Punjab','Faridkot','District-wide'),
('Punjab','Fatehgarh Sahib','District-wide'),
('Punjab','Fazilka','District-wide'),
('Punjab','Ferozepur','District-wide'),
('Punjab','Gurdaspur','District-wide'),
('Punjab','Hoshiarpur','District-wide'),
('Punjab','Jalandhar','District-wide'),
('Punjab','Kapurthala','District-wide'),
('Punjab','Ludhiana','District-wide'),
('Punjab','Malerkotla','District-wide'),
('Punjab','Mansa','District-wide'),
('Punjab','Moga','District-wide'),
('Punjab','Pathankot','District-wide'),
('Punjab','Patiala','District-wide'),
('Punjab','Rupnagar','District-wide'),
('Punjab','S.A.S Nagar','District-wide'),
('Punjab','Sangrur','District-wide'),
('Punjab','Shahid Bhagat Singh Nagar','District-wide'),
('Punjab','Sri Muktsar Sahib','District-wide'),
('Punjab','Tarn Taran','District-wide'),
('Madhya Pradesh','Agar-Malwa','District-wide'),
('Madhya Pradesh','Alirajpur','District-wide'),
('Madhya Pradesh','Anuppur','District-wide'),
('Madhya Pradesh','Ashoknagar','District-wide'),
('Madhya Pradesh','Balaghat','District-wide'),
('Madhya Pradesh','Barwani','District-wide'),
('Madhya Pradesh','Betul','District-wide'),
('Madhya Pradesh','Bhind','District-wide'),
('Madhya Pradesh','Bhopal','District-wide'),
('Madhya Pradesh','Burhanpur','District-wide'),
('Madhya Pradesh','Chhatarpur','District-wide'),
('Madhya Pradesh','Chhindwara','District-wide'),
('Madhya Pradesh','Damoh','District-wide'),
('Madhya Pradesh','Datia','District-wide'),
('Madhya Pradesh','Dewas','District-wide'),
('Madhya Pradesh','Dhar','District-wide'),
('Madhya Pradesh','Dindori','District-wide'),
('Madhya Pradesh','Guna','District-wide'),
('Madhya Pradesh','Gwalior','District-wide'),
('Madhya Pradesh','Harda','District-wide'),
('Madhya Pradesh','Indore','District-wide'),
('Madhya Pradesh','Jabalpur','District-wide'),
('Madhya Pradesh','Jhabua','District-wide'),
('Madhya Pradesh','Katni','District-wide'),
('Madhya Pradesh','Khandwa (East Nimar)','District-wide'),
('Madhya Pradesh','Khargone (West Nimar)','District-wide'),
('Madhya Pradesh','MAUGANJ','District-wide'),
('Madhya Pradesh','Maihar','District-wide'),
('Madhya Pradesh','Mandla','District-wide'),
('Madhya Pradesh','Mandsaur','District-wide'),
('Madhya Pradesh','Morena','District-wide'),
('Madhya Pradesh','Narmadapuram','District-wide'),
('Madhya Pradesh','Narsimhapur','District-wide'),
('Madhya Pradesh','Neemuch','District-wide'),
('Madhya Pradesh','Niwari','District-wide'),
('Madhya Pradesh','Pandhurna','District-wide'),
('Madhya Pradesh','Panna','District-wide'),
('Madhya Pradesh','Raisen','District-wide'),
('Madhya Pradesh','Rajgarh','District-wide'),
('Madhya Pradesh','Ratlam','District-wide'),
('Madhya Pradesh','Rewa','District-wide'),
('Madhya Pradesh','Sagar','District-wide'),
('Madhya Pradesh','Satna','District-wide'),
('Madhya Pradesh','Sehore','District-wide'),
('Madhya Pradesh','Seoni','District-wide'),
('Madhya Pradesh','Shahdol','District-wide'),
('Madhya Pradesh','Shajapur','District-wide'),
('Madhya Pradesh','Sheopur','District-wide'),
('Madhya Pradesh','Shivpuri','District-wide'),
('Madhya Pradesh','Sidhi','District-wide'),
('Madhya Pradesh','Singrauli','District-wide'),
('Madhya Pradesh','Tikamgarh','District-wide'),
('Madhya Pradesh','Ujjain','District-wide'),
('Madhya Pradesh','Umaria','District-wide'),
('Madhya Pradesh','Vidisha','District-wide'),
('Odisha','Anugola','District-wide'),
('Odisha','Balangir','District-wide'),
('Odisha','Baleshwar','District-wide'),
('Odisha','Baragada','District-wide'),
('Odisha','Bhadrak','District-wide'),
('Odisha','Boudh','District-wide'),
('Odisha','Debagada','District-wide'),
('Odisha','Dhenkanal','District-wide'),
('Odisha','Gajapati','District-wide'),
('Odisha','Ganjam','District-wide'),
('Odisha','Jagatsinghapur','District-wide'),
('Odisha','Jajpur','District-wide'),
('Odisha','Jharsuguda','District-wide'),
('Odisha','Kalahandi','District-wide'),
('Odisha','Kandhamala','District-wide'),
('Odisha','Kataka','District-wide'),
('Odisha','Kendrapada','District-wide'),
('Odisha','Kendujhar','District-wide'),
('Odisha','Khordha','District-wide'),
('Odisha','Koraput','District-wide'),
('Odisha','Malkangiri','District-wide'),
('Odisha','Mayurbhanj','District-wide'),
('Odisha','Nabarangpur','District-wide'),
('Odisha','Nayagada','District-wide'),
('Odisha','Nuapada','District-wide'),
('Odisha','Puri','District-wide'),
('Odisha','Rayagada','District-wide'),
('Odisha','Sambalpur','District-wide'),
('Odisha','Subarnapur','District-wide'),
('Odisha','Sundaragada','District-wide'),
('Sikkim','Gangtok','District-wide'),
('Sikkim','Gyalshing','District-wide'),
('Sikkim','Mangan','District-wide'),
('Sikkim','Namchi','District-wide'),
('Sikkim','Pakyong','District-wide'),
('Sikkim','Soreng','District-wide'),
('Telangana','Adilabad','District-wide'),
('Telangana','Bhadradri Kothagudem','District-wide'),
('Telangana','Hanumakonda','District-wide'),
('Telangana','Hyderabad','District-wide'),
('Telangana','Jagitial','District-wide'),
('Telangana','Jangoan','District-wide'),
('Telangana','Jayashankar Bhupalapally','District-wide'),
('Telangana','Jogulamba Gadwal','District-wide'),
('Telangana','Kamareddy','District-wide'),
('Telangana','Karimnagar','District-wide'),
('Telangana','Khammam','District-wide'),
('Telangana','Kumuram Bheem Asifabad','District-wide'),
('Telangana','Mahabubabad','District-wide'),
('Telangana','Mahabubnagar','District-wide'),
('Telangana','Mancherial','District-wide'),
('Telangana','Medak','District-wide'),
('Telangana','Medchal Malkajgiri','District-wide'),
('Telangana','Mulugu','District-wide'),
('Telangana','Nagarkurnool','District-wide'),
('Telangana','Nalgonda','District-wide'),
('Telangana','Narayanpet','District-wide'),
('Telangana','Nirmal','District-wide'),
('Telangana','Nizamabad','District-wide'),
('Telangana','Peddapalli','District-wide'),
('Telangana','Rajanna Sircilla','District-wide'),
('Telangana','Ranga Reddy','District-wide'),
('Telangana','Sangareddy','District-wide'),
('Telangana','Siddipet','District-wide'),
('Telangana','Suryapet','District-wide'),
('Telangana','Vikarabad','District-wide'),
('Telangana','Wanaparthy','District-wide'),
('Telangana','Warangal','District-wide'),
('Telangana','Yadadri Bhuvanagiri','District-wide'),
('Tripura','Dhalai','District-wide'),
('Tripura','Gomati','District-wide'),
('Tripura','Khowai','District-wide'),
('Tripura','North Tripura','District-wide'),
('Tripura','Sepahijala','District-wide'),
('Tripura','South Tripura','District-wide'),
('Tripura','Unakoti','District-wide'),
('Tripura','West Tripura','District-wide'),
('Rajasthan','Ajmer','District-wide'),
('Rajasthan','Alwar','District-wide'),
('Rajasthan','Balotra','District-wide'),
('Rajasthan','Banswara','District-wide'),
('Rajasthan','Baran','District-wide'),
('Rajasthan','Barmer','District-wide'),
('Rajasthan','Beawar','District-wide'),
('Rajasthan','Bharatpur','District-wide'),
('Rajasthan','Bhilwara','District-wide'),
('Rajasthan','Bikaner','District-wide'),
('Rajasthan','Bundi','District-wide'),
('Rajasthan','Chittorgarh','District-wide'),
('Rajasthan','Churu','District-wide'),
('Rajasthan','Dausa','District-wide'),
('Rajasthan','Deeg','District-wide'),
('Rajasthan','Dholpur','District-wide'),
('Rajasthan','Didwana-Kuchaman','District-wide'),
('Rajasthan','Dungarpur','District-wide'),
('Rajasthan','Ganganagar','District-wide'),
('Rajasthan','Hanumangarh','District-wide'),
('Rajasthan','Jaipur','District-wide'),
('Rajasthan','Jaisalmer','District-wide'),
('Rajasthan','Jalore','District-wide'),
('Rajasthan','Jhalawar','District-wide'),
('Rajasthan','Jhunjhunu','District-wide'),
('Rajasthan','Jodhpur','District-wide'),
('Rajasthan','Karauli','District-wide'),
('Rajasthan','Khairthal-Tijara','District-wide'),
('Rajasthan','Kota','District-wide'),
('Rajasthan','Kotputli-Behror','District-wide'),
('Rajasthan','Nagaur','District-wide'),
('Rajasthan','Pali','District-wide'),
('Rajasthan','Phalodi','District-wide'),
('Rajasthan','Pratapgarh','District-wide'),
('Rajasthan','Rajsamand','District-wide'),
('Rajasthan','Salumbar','District-wide'),
('Rajasthan','Sawai Madhopur','District-wide'),
('Rajasthan','Sikar','District-wide'),
('Rajasthan','Sirohi','District-wide'),
('Rajasthan','Tonk','District-wide'),
('Rajasthan','Udaipur','District-wide'),
('Uttarakhand','Almora','District-wide'),
('Uttarakhand','Bageshwar','District-wide'),
('Uttarakhand','Chamoli','District-wide'),
('Uttarakhand','Champawat','District-wide'),
('Uttarakhand','Dehradun','District-wide'),
('Uttarakhand','Haridwar','District-wide'),
('Uttarakhand','Nainital','District-wide'),
('Uttarakhand','Pauri Garhwal','District-wide'),
('Uttarakhand','Pithoragarh','District-wide'),
('Uttarakhand','Rudraprayag','District-wide'),
('Uttarakhand','Tehri Garhwal','District-wide'),
('Uttarakhand','Udham Singh Nagar','District-wide'),
('Uttarakhand','Uttarkashi','District-wide'),
('Tamil Nadu','Ariyalur','District-wide'),
('Tamil Nadu','Chengalpattu','District-wide'),
('Tamil Nadu','Chennai','District-wide'),
('Tamil Nadu','Coimbatore','District-wide'),
('Tamil Nadu','Cuddalore','District-wide'),
('Tamil Nadu','Dharmapuri','District-wide'),
('Tamil Nadu','Dindigul','District-wide'),
('Tamil Nadu','Erode','District-wide'),
('Tamil Nadu','Kallakurichi','District-wide'),
('Tamil Nadu','Kancheepuram','District-wide'),
('Tamil Nadu','Kanniyakumari','District-wide'),
('Tamil Nadu','Karur','District-wide'),
('Tamil Nadu','Krishnagiri','District-wide'),
('Tamil Nadu','Madurai','District-wide'),
('Tamil Nadu','Mayiladuthurai','District-wide'),
('Tamil Nadu','Nagapattinam','District-wide'),
('Tamil Nadu','Namakkal','District-wide'),
('Tamil Nadu','Perambalur','District-wide'),
('Tamil Nadu','Pudukkottai','District-wide'),
('Tamil Nadu','Ramanathapuram','District-wide'),
('Tamil Nadu','Ranipet','District-wide'),
('Tamil Nadu','Salem','District-wide'),
('Tamil Nadu','Sivaganga','District-wide'),
('Tamil Nadu','Tenkasi','District-wide'),
('Tamil Nadu','Thanjavur','District-wide'),
('Tamil Nadu','The Nilgiris','District-wide'),
('Tamil Nadu','Theni','District-wide'),
('Tamil Nadu','Thiruvallur','District-wide'),
('Tamil Nadu','Thiruvarur','District-wide'),
('Tamil Nadu','Thoothukkudi','District-wide'),
('Tamil Nadu','Tiruchirappalli','District-wide'),
('Tamil Nadu','Tirunelveli','District-wide'),
('Tamil Nadu','Tirupathur','District-wide'),
('Tamil Nadu','Tiruppur','District-wide'),
('Tamil Nadu','Tiruvannamalai','District-wide'),
('Tamil Nadu','Vellore','District-wide'),
('Tamil Nadu','Viluppuram','District-wide'),
('Tamil Nadu','Virudhunagar','District-wide'),
('West Bengal','Alipurduar','District-wide'),
('West Bengal','Bankura','District-wide'),
('West Bengal','Birbhum','District-wide'),
('West Bengal','Cooch Behar','District-wide'),
('West Bengal','Dakshin Dinajpur','District-wide'),
('West Bengal','Darjeeling','District-wide'),
('West Bengal','Hooghly','District-wide'),
('West Bengal','Howrah','District-wide'),
('West Bengal','Jalpaiguri','District-wide'),
('West Bengal','Jhargram','District-wide'),
('West Bengal','Kalimpong','District-wide'),
('West Bengal','Kolkata','District-wide'),
('West Bengal','Malda','District-wide'),
('West Bengal','Murshidabad','District-wide'),
('West Bengal','Nadia','District-wide'),
('West Bengal','North 24 Parganas','District-wide'),
('West Bengal','Paschim Bardhaman','District-wide'),
('West Bengal','Paschim Medinipur','District-wide'),
('West Bengal','Purba Bardhaman','District-wide'),
('West Bengal','Purba Medinipur','District-wide'),
('West Bengal','Purulia','District-wide'),
('West Bengal','South 24 Parganas','District-wide'),
('West Bengal','Uttar Dinajpur','District-wide'),
('Uttar Pradesh','Agra','District-wide'),
('Uttar Pradesh','Aligarh','District-wide'),
('Uttar Pradesh','Ambedkar Nagar','District-wide'),
('Uttar Pradesh','Amethi','District-wide'),
('Uttar Pradesh','Amroha','District-wide'),
('Uttar Pradesh','Auraiya','District-wide'),
('Uttar Pradesh','Ayodhya','District-wide'),
('Uttar Pradesh','Azamgarh','District-wide'),
('Uttar Pradesh','Baghpat','District-wide'),
('Uttar Pradesh','Bahraich','District-wide'),
('Uttar Pradesh','Ballia','District-wide'),
('Uttar Pradesh','Balrampur','District-wide'),
('Uttar Pradesh','Banda','District-wide'),
('Uttar Pradesh','Bara Banki','District-wide'),
('Uttar Pradesh','Bareilly','District-wide'),
('Uttar Pradesh','Basti','District-wide'),
('Uttar Pradesh','Bhadohi','District-wide'),
('Uttar Pradesh','Bijnor','District-wide'),
('Uttar Pradesh','Budaun','District-wide'),
('Uttar Pradesh','Bulandshahr','District-wide'),
('Uttar Pradesh','Chandauli','District-wide'),
('Uttar Pradesh','Chitrakoot','District-wide'),
('Uttar Pradesh','Deoria','District-wide'),
('Uttar Pradesh','Etah','District-wide'),
('Uttar Pradesh','Etawah','District-wide'),
('Uttar Pradesh','Farrukhabad','District-wide'),
('Uttar Pradesh','Fatehpur','District-wide'),
('Uttar Pradesh','Firozabad','District-wide'),
('Uttar Pradesh','Gautam Buddha Nagar','District-wide'),
('Uttar Pradesh','Ghaziabad','District-wide'),
('Uttar Pradesh','Ghazipur','District-wide'),
('Uttar Pradesh','Gonda','District-wide'),
('Uttar Pradesh','Gorakhpur','District-wide'),
('Uttar Pradesh','Hamirpur','District-wide'),
('Uttar Pradesh','Hapur','District-wide'),
('Uttar Pradesh','Hardoi','District-wide'),
('Uttar Pradesh','Hathras','District-wide'),
('Uttar Pradesh','Jalaun','District-wide'),
('Uttar Pradesh','Jaunpur','District-wide'),
('Uttar Pradesh','Jhansi','District-wide'),
('Uttar Pradesh','Kannauj','District-wide'),
('Uttar Pradesh','Kanpur Dehat','District-wide'),
('Uttar Pradesh','Kanpur Nagar','District-wide'),
('Uttar Pradesh','Kasganj','District-wide'),
('Uttar Pradesh','Kaushambi','District-wide'),
('Uttar Pradesh','Kheri','District-wide'),
('Uttar Pradesh','Kushinagar','District-wide'),
('Uttar Pradesh','Lalitpur','District-wide'),
('Uttar Pradesh','Lucknow','District-wide'),
('Uttar Pradesh','Mahoba','District-wide'),
('Uttar Pradesh','Mahrajganj','District-wide'),
('Uttar Pradesh','Mainpuri','District-wide'),
('Uttar Pradesh','Mathura','District-wide'),
('Uttar Pradesh','Mau','District-wide'),
('Uttar Pradesh','Meerut','District-wide'),
('Uttar Pradesh','Mirzapur','District-wide'),
('Uttar Pradesh','Moradabad','District-wide'),
('Uttar Pradesh','Muzaffarnagar','District-wide'),
('Uttar Pradesh','Pilibhit','District-wide'),
('Uttar Pradesh','Pratapgarh','District-wide'),
('Uttar Pradesh','Prayagraj','District-wide'),
('Uttar Pradesh','Rae Bareli','District-wide'),
('Uttar Pradesh','Rampur','District-wide'),
('Uttar Pradesh','Saharanpur','District-wide'),
('Uttar Pradesh','Sambhal','District-wide'),
('Uttar Pradesh','Sant Kabir Nagar','District-wide'),
('Uttar Pradesh','Shahjahanpur','District-wide'),
('Uttar Pradesh','Shamli','District-wide'),
('Uttar Pradesh','Shrawasti','District-wide'),
('Uttar Pradesh','Siddharthnagar','District-wide'),
('Uttar Pradesh','Sitapur','District-wide'),
('Uttar Pradesh','Sonbhadra','District-wide'),
('Uttar Pradesh','Sultanpur','District-wide'),
('Uttar Pradesh','Unnao','District-wide'),
('Uttar Pradesh','Varanasi','District-wide')
on conflict (state,district,city) do nothing;
